### ISSUE TITLE
Documentation not updated upon release

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-r-armadillo#105]
When we moved to CircleCI, we had to replace a deprecated function used to publish documentation in the Jenkins Config:

```
pkgdown::deploy_site_github(ssh_id = '${GITHUB_DEPLOY_PRIVATE_KEY_BASE64}', tarball = '${PACKAGE}_${TAG}.tar.gz', repo_slug='${REPOSITORY}')
```

We attempted to replace it with the suggested replacement: [usethis::use_pkgdown_github_pages()](https://usethis.r-lib.org/reference/use_pkgdown.html)

This one however is used to configure the github.io via github actions, but we want to deploy it on our gh-pages branch.

It is possible to publish github.io manually using [deploy_to_branch()](https://pkgdown.r-lib.org/reference/deploy_to_branch.html). 

This one however does not work in the CI and has to be run locally.

The only way to properly test if it works seems to be merging a PR that will create a release (fix) to the master.

I've tried testing it with a publishing on a gh-pages-dev [branch](https://github.com/molgenis/molgenis-r-armadillo/tree/gh-pages-dev) on PR.

You cannot see that one as a github.io, but pushing locally to that branch using the deploy_to_branch function does work.

CI also fails on the gh-pages branch (because there is no ci config), not sure how to fix that either.

**Comment by clemens-tolboom** [comment]
See PR #102

**Comment by clemens-tolboom** [comment]
Error is about 

```txt
-- Building home ---------------------------------------------------------------
Writing 'authors.html'
Writing '404.html'
-- Building function reference -------------------------------------------------
Writing 'reference/index.html'

Error in library(pkg$package, character.only = TRUE) : 
  there is no package called ‘MolgenisArmadillo’

Running new PR from master #106 does not continu into intended `exit`
Calls: <Anonymous> ... build_site_local -> build_reference -> examples_env -> library
11 Removing worktree 11111111111111111111111111111111111111111111111111111111111
Running git worktree remove /tmp/RtmpLBxqdW/file49f6376ff8ed
Execution halted

Exited with code exit status 1
```

## New PR

Creating a new PR #106 does fail before intended `exit 1`

See https://app.circleci.com/pipelines/github/molgenis/molgenis-r-armadillo/173

### Log warnings/errors

> Testing MolgenisArmadillo:2.3.0
---
ℹ Installed roxygen2 version (7.1.2) doesn't match required version (7.2.3)
✖ check() will not re-document this package
---

And a little down

> Insufficient package version (submitted: 2.3.0, existing: 2.3.0)

And lastly similar

```
❯ checking CRAN incoming feasibility ... WARNING
  Maintainer: ‘Mariska Slofstra <m.k.slofstra@umcg.nl>’
  
  Insufficient package version (submitted: 2.3.0, existing: 2.3.0)

0 errors ✔ | 1 warning ✖ | 0 notes ✔
Error: R CMD check found WARNINGs
Execution halted
```

**Comment by clemens-tolboom** [comment]
![image](https://github.com/molgenis/molgenis-r-armadillo/assets/371014/327a39ab-ba4c-489c-85f0-7fc5b10c010e)

**Comment by clemens-tolboom** [comment]
What is wrong with using GitHub action?

In PR #108 I allowed this and they are push into https://github.com/molgenis/molgenis-r-armadillo/tree/gh-pages-dev

**Comment by clemens-tolboom** [comment]
Closing as we build through GitHub actions now.
