### ISSUE TITLE
gh pages version does not use latest tag (v.2.3.2)

### ISSUE THREAD

**Issue by clemens-tolboom** [molgenis/molgenis-r-armadillo#110]
The version v2.1.4 on

- https://molgenis.github.io/molgenis-r-armadillo/

does not match latest commit on

- https://github.com/molgenis/molgenis-r-armadillo/tree/gh-pages

which should be v2.3.2 at this moment

- https://github.com/molgenis/molgenis-r-armadillo/tags

**Comment by clemens-tolboom** [comment]
```sh
grep -r 2.1.4 . | cut -c -100
Binary file ./vignettes/data/core/monthlyrep.parquet matches
./DESCRIPTION:Version: 2.1.4
./.gitignore:/MolgenisArmadillo_2.1.4.tar.gz
```

Guess we should edit the version manually

**Comment by timcadman** [comment]
GH pages builds based on the version number in the DESCRIPTION file, so is currently working correctly. Fixing issue #114 will align description file with current release.
