### ISSUE TITLE
In armadillo.create_project(), existing project is overwritten without warning

### ISSUE THREAD

**Issue by timcadman** [molgenis/molgenis-r-armadillo#91]
Currently if you call armadillo.create_project() and provide the name of an existing project, it simply overwrites this project without providing a warning. Could this be changed so that the user is given the option whether to proceed with overwriting, or abort?

Thanks!

**Comment by clemens-tolboom** [comment]
Hmmm ... I think it is backend bug so reported https://github.com/molgenis/molgenis-service-armadillo/issues/550

What do you think?
